apps/base/urls.py
from django.urls import path
from base.views import StaticHome

urlpatterns = [
    path('', StaticHome.as_view(), name='home'),
]

apps/dashboard/urls.py
from django.urls import path
from dashboard.views import Home
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='dashboard/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='dashboard/login.html'), name='logout'),
]

apps/static_home/urls.py
from django.urls import path
from static_home.views import Home
from . import views

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('team/', views.team, name="team"),
    path('contact/', views.contact, name="contact"),
]

backenderp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('apps.static_home.urls', 'static_home'), namespace='static_home')),
    path('admin/', include(('apps.dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('admin/stock/', include(('apps.stock.urls', 'stock'), namespace='stock')),
    path('admin-django/', admin.site.urls),
]

apps/base/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class ClassModel(models.Model):
    state = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)

    uc = models.ForeignKey(User, on_delete=models.CASCADE )
    um = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract = True

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/stock/models/brand.py
from django.db import models
from base.models import ClassModel


class Brand(ClassModel):
    name = models.CharField(max_length=100, 
    unique=True,
    help_text='Name of Brand')

    parent_id = models.ForeignKey('self',  
    on_delete=models.PROTECT,
    verbose_name=('Parent'),
    null=True,
    blank=True,
    related_name='children')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'
        ordering = ['name']

apps/stock/models/category.py
from django.db import models
from base.models import ClassModel


class Category(ClassModel):
    name = models.CharField(max_length=100, 
    unique=True,
    help_text='Name of category')

    for_website = models.BooleanField(default=False,
    help_text='Show on website')

    for_stock = models.BooleanField(default=True,
    help_text='Show on stock')

    parent_id = models.ForeignKey('self',  
    on_delete=models.PROTECT,
    verbose_name=('Parent'),
    null=True,
    blank=True,
    related_name='children')

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'category'
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['name']
    

apps/stock/models/location.py
from django.db import models
from base.models import ClassModel
from stock.models.warehouse import Warehouse


class Location(ClassModel):
    name = models.CharField(max_length=100, 
    unique=True,
    help_text='Name of location')

    warehouse_id = models.ForeignKey(
        Warehouse,
        related_name='location',
        on_delete=models.PROTECT,
        verbose_name='Warehouse',
        null=True,
        blank=True
    )

    parent_id = models.ForeignKey('self',  
    on_delete=models.PROTECT,
    verbose_name=('Parent'),
    null=True,
    blank=True,
    related_name='children')

    code = models.CharField(max_length=3,
    unique=True,
    help_text='Code')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Location'
        verbose_name_plural = 'Locations'
        ordering = ['name']

apps/stock/models/model.py
from django.db import models
from base.models import ClassModel
from stock.models.brand import Brand


class Model(ClassModel):
    name = models.CharField(max_length=100, 
    unique=True,
    help_text='Name of the model')

    brand_id = models.ForeignKey(
        Brand,
        related_name='brand',
        on_delete=models.PROTECT,
        verbose_name='Brand',
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Model'
        verbose_name_plural = 'Models'
        ordering = ['name']

apps/stock/models/product.py
from django.db import models
from base.models import ClassModel
# from stock.models.category import Category

PRODUCT_TYPE = (
        ('service', 'Service'),
        ('product', 'Product'),
        ('cons', 'Consumable'),
    )


class Product(ClassModel):
    name = models.CharField(max_length=100, 
    unique=True,
    help_text='Name of Product')

    type = models.CharField(
        choices=PRODUCT_TYPE, max_length=100, default='product')

    # category_id = models.ForeignKey(
    #     Category,
    #     on_delete=models.PROTECT,
    #     verbose_name=('Category'),
    #     null=True,
    #     blank=True
    # )
    

    def __str__(self):
        return self.name

    class Meta:
        # app_label = 'products'
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ['name']

    for_sale = models.BooleanField(default=True)
    for_purchase = models.BooleanField(default=True)

    code = models.CharField(max_length=100,
    unique=True,
    null=True,
    blank=True,
    help_text='Code of Product')

    barcode = models.CharField(max_length=100,
    unique=True,
    null=True,
    blank=True,
    help_text='Barcode of Product')

    description = models.TextField(
        max_length=500,
        null=True,
        blank=True,
        help_text='Description of Product')

apps/stock/models/uom.py
from django.db import models
from base.models import ClassModel


class Uom(ClassModel):
    name = models.CharField(max_length=100, 
    unique=True,
    help_text='Name of Uom')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Uom'
        verbose_name_plural = 'Uoms'
        ordering = ['name']

apps/stock/models/warehouse.py
from django.db import models
from base.models import ClassModel

class Warehouse(ClassModel):
    name = models.CharField(max_length=100, 
    unique=True,
    help_text='Name of Warehouse')

    code = models.CharField(max_length=3,
    unique=True,
    null=True,
    blank=True,
    help_text='Code')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Warehouse'
        verbose_name_plural = 'Warehouses'
        ordering = ['name']

apps/stock/forms/product.py
from django import forms
from ..models.product import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = PyProduct
        fields = [
            'name',
            'code',
            'carcode',
            'description',
        ]

apps/base/views.py
from django.shortcuts import render

from django.views import generic

class StaticHome(generic.TemplateView):
    template_name = 'base/home.html'

apps/dashboard/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'dashboard/home.html'
    login_url = '/admin/login'

apps/static_home/views.py
from django.shortcuts import render
from django.views import generic

class Home(generic.TemplateView):
    # template_name = 'base/base.html'
    template_name = 'static_home/home.html'

def page_not_found_view(request, exception):
    return render(request, 'base/404.html', status=404)

def contact(request):
    return render(request, 'base/contact.html')

def team(request):
    return render(request, 'base/team.html')

apps/stock/views/product.py
from django.contrib.auth.mixins import LoginRequiredMixin
from ..models import Product

OBJECT_LIST_FIELDS = [
    {'string': _("Code"), 'field': 'code'},
    {'string': _("Bar Code"), 'field': 'barcode'},
    {'string': _("Name"), 'field': 'name'},
]

OBJECT_FORM_FIELDS = [
    'name',
    'code',
    'barcode',
    'description',
]

class ProductListView(LoginRequiredMixin, FatherListView):
    model = Product
    template_name = 'base/list.html'
    extra_context = {'fields': OBJECT_LIST_FIELDS}

apps/static_home/templates/static_home/home.html
{% extends 'base/base.html' %}
{% load static %}


{% block container %}
<div>
 <h3>API documentation</h3>
<hr/>

</div>
{% endblock container %}

templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
  {% include 'base/include/head.html' %}  

  <body>
    {% include 'base/include/navbar.html' %}
    

    <div class="container">
    {% block container %}

    
      
    {% endblock container %}


    {% include 'base/include/footer.html' %}  
    </div>
    


    {% block js %}
    <script src="{% static 'base/vendor/bootstrap/js/jquery-3.2.1.slim.min.js' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="{% static 'base/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
    {% endblock js %} 
  </body>
</html>

templates/base/contact.html
{% extends 'base/base.html' %}
{% load static %}

{% block container %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="lead">Marlon Falcon Hernandez</p>
    <p class="lead">mfalconsoft@gmail.com</p>
    <p>+34 (662) 470645</p>
  </div>

{% endblock container %}

templates/base/include/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        {% comment %} <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24"> {% endcomment %}
        <small class="d-block mb-3 text-muted">&copy; BackendERP 2023</small>
      </div>
      <div class="col-6 col-md">
        <h5>Code</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="https://github.com/falconsoft3d/backenderp">Git Repository</a></li>
          <li><a class="text-muted" href="https://github.com/falconsoft3d/backenderp/issues">Bugs</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>API</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Documentation</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </footer>

templates/base/include/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">
    <title>BackendERP | your backend</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">
    <link href="{% static 'base/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="pricing.css" rel="stylesheet">
  
    <script type='text/javascript'>
      //some default pre init
      var Countly = Countly || {};
      Countly.q = Countly.q || [];
      
      //provide countly initialization parameters
      Countly.app_key = 'fa8e539dbe8857d6fb2fde390bb249df2ca45838';
      Countly.url = 'https://countly.backenderp.com';
      
      Countly.q.push(['track_sessions']);
      Countly.q.push(['track_pageview']);
      Countly.q.push(['track_clicks']);
      Countly.q.push(['track_scrolls']);
      Countly.q.push(['track_errors']);
      Countly.q.push(['track_links']);
      Countly.q.push(['track_forms']);
      Countly.q.push(['collect_from_forms']);
      
      //load countly script asynchronously
      (function() {
         var cly = document.createElement('script'); cly.type = 'text/javascript';
         cly.async = true;
         //enter url of script here
         cly.src = 'https://countly.backenderp.com/sdk/web/countly.min.js';
         cly.onload = function(){Countly.init()};
         var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(cly, s);
      })();
      </script>
  
  </head>

templates/base/include/navbar.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">BackendERP</h5>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="/">Home</a>
      <a class="p-2 text-dark" href="/team">Team</a>
      <a class="p-2 text-dark" href="/contact">Contact</a>
    </nav>
    <a class="btn btn-outline-primary" href="https://github.com/falconsoft3d/backenderp">Code</a>
  </div>

templates/base/team.html
{% extends 'base/base.html' %}
{% load static %}

{% block container %}

<div class="container" style="margin-top: 50px;">
    <p class="lead">Marlon Falcon Hernandez</p>
</div>

{% endblock container %}

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% include 'dashboard/include/head.html' %}  

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        {% include 'dashboard/include/sidebar.html' %}  
        

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    {% comment %} {% include 'dashboard/include/search.html' %}   {% endcomment %}

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        
                        {% comment %} {% include 'dashboard/include/alert.html' %}   {% endcomment %}

                        <!-- Nav Item - Messages -->
                        
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                    src="{% static 'dashboard/img/undraw_profile.svg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% block container %}
                       
                    {% endblock container %}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            {% include 'dashboard/include/footer.html' %}  

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'dashboard:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    {% include 'dashboard/include/javascript.html' %}

</body>

</html>

templates/dashboard/home.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block container %}
  <h1 class="h3 mb-4 text-gray-800">Dashboard</h1>
{% endblock container %}

templates/dashboard/include/alert.html
{% load static %}
<li class="nav-item dropdown no-arrow mx-1">
    <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <!-- Counter - Messages -->
        <span class="badge badge-danger badge-counter">7</span>
    </a>
    <!-- Dropdown - Messages -->
    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
        aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
            Message Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="{% static 'dashboard/img/undraw_profile_1.svg' %}"
                    alt="...">
                <div class="status-indicator bg-success"></div>
            </div>
            <div class="font-weight-bold">
                <div class="text-truncate">Hi there! I am wondering if you can help me with a
                    problem I've been having.</div>
                <div class="small text-gray-500">Emily Fowler · 58m</div>
            </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="{% static 'dashboard/img/undraw_profile_2.svg' %}"
                    alt="...">
                <div class="status-indicator"></div>
            </div>
            <div>
                <div class="text-truncate">I have the photos that you ordered last month, how
                    would you like them sent to you?</div>
                <div class="small text-gray-500">Jae Chun · 1d</div>
            </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="{% static 'dashboard/img/undraw_profile_3.svg' %}"
                    alt="...">
                <div class="status-indicator bg-warning"></div>
            </div>
            <div>
                <div class="text-truncate">Last month's report looks great, I am very happy with
                    the progress so far, keep up the good work!</div>
                <div class="small text-gray-500">Morgan Alvarez · 2d</div>
            </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
            <div class="dropdown-list-image mr-3">
                <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                    alt="...">
                <div class="status-indicator bg-success"></div>
            </div>
            <div>
                <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                    told me that people say this to all dogs, even if they aren't good...</div>
                <div class="small text-gray-500">Chicken the Dog · 2w</div>
            </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
    </div>
</li>

templates/dashboard/include/footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span><b>BackendERP</b> &copy; <a href="https://www.backendERP.com">backendERP.com</a> 2023</span>
        </div>
    </div>
</footer>

templates/dashboard/include/head.html
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ settings.APP_NAME }}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'dashboard/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'dashboard/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

templates/dashboard/include/javascript.html
{% load static %}
<script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'dashboard/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'dashboard/js/sb-admin-2.min.js' %}"></script>

templates/dashboard/include/messages.html
{% load static %}
<i class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-envelope fa-fw"></i>
                                <!-- Counter - Messages -->
                                <span class="badge badge-danger badge-counter">7</span>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="messagesDropdown">
                                <h6 class="dropdown-header">
                                    Message Center
                                </h6>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="{% static 'dashboard/img/undraw_profile_1.svg' %}"
                                            alt="...">
                                        <div class="status-indicator bg-success"></div>
                                    </div>
                                    <div class="font-weight-bold">
                                        <div class="text-truncate">Hi there! I am wondering if you can help me with a
                                            problem I've been having.</div>
                                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="{% static 'dashboard/img/undraw_profile_2.svg' %}"
                                            alt="...">
                                        <div class="status-indicator"></div>
                                    </div>
                                    <div>
                                        <div class="text-truncate">I have the photos that you ordered last month, how
                                            would you like them sent to you?</div>
                                        <div class="small text-gray-500">Jae Chun · 1d</div>
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="{% static 'dashboard/img/undraw_profile_3.svg' %}"
                                            alt="...">
                                        <div class="status-indicator bg-warning"></div>
                                    </div>
                                    <div>
                                        <div class="text-truncate">Last month's report looks great, I am very happy with
                                            the progress so far, keep up the good work!</div>
                                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                                            alt="...">
                                        <div class="status-indicator bg-success"></div>
                                    </div>
                                    <div>
                                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                                            told me that people say this to all dogs, even if they aren't good...</div>
                                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                                    </div>
                                </a>
                                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                            </div>
                        </li>

templates/dashboard/include/search.html
<form
class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
<div class="input-group">
    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
        aria-label="Search" aria-describedby="basic-addon2">
    <div class="input-group-append">
        <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
        </button>
    </div>
</div>
</form>

templates/static_home/home.html
{% extends 'base/base.html' %}
{% load static %}


{% block container %}
<div>
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">BackendERP</h1>
        <p class="lead">A generic backend for your erp in <b>Django</b> & <b>Python</b></p>
    </div>
</div>
{% endblock container %}